[log]
use_wandb = false
wandb_project = "baysic"
use_directory = true
log_directory = "logs"
log_dir_mode = "append"

[search]
n_parallel_structs = 500
n_grid = 12
wyckoff_strategy = "fewer_distinct"
smoke_test = false
num_generations = 50
max_gens_at_once = 10
allowed_attempts_per_gen = 5.0
lattice_scale_factor_mu = 1.1
lattice_scale_factor_sigma = 0.47
order_positions_by_radius = false

[target]
mp_id = "mp-66"

[cli]
verbosity = "info"
show_progress = true
