[log]
log_dir_mode = "append"

[search]
num_generations = 150
allowed_attempts_per_gen = 5.0
max_gens_at_once = 15
order_positions_by_radius = true
wyckoff_strategy = 'sample_distinct'

[device]
device = "cuda"
