[log]
use_wandb = false
wandb_project = "baysic"
use_directory = true
log_directory = "logs"
log_dir_mode = "append"

[search]
n_parallel_structs = 500
n_grid = 12
wyckoff_strategy = "sample_distinct"
smoke_test = false
num_generations = 50
max_gens_at_once = 10
allowed_attempts_per_gen = 10.0
order_positions_by_radius = true

[target]
mp_id = "mp-XXXXX"

[cli]
verbosity = "info"
show_progress = true

[device]
device = "cpu"
